# Generated by Django 2.2.6 on 2024-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/9187/9187604.png', upload_to='profile_pics'),
        ),
    ]
